### ISSUE TITLE
File "learning_wavelets.keras_utils.filters_cback" missing

### ISSUE THREAD

**Issue by sophie7** [zaccharieramzi/understanding-unets#45]
Hi,

nice work! But when I tried to run the "experiments/learnlet_dynamic_denoising.ipynb", the file "learning_wavelets.keras_utils.filters_cback" is missing.

Could you please check it?

Thanks.

Regards

**Comment by zaccharieramzi** [comment]
Hi @sophie7 ,

Thanks for your interest in the repo.
Indeed, this file is missing and the notebook is not up to date. I would advise to rather use [the scripts available in `training_scripts`](https://github.com/zaccharieramzi/understanding-unets/tree/master/learning_wavelets/training_scripts), which are more recent.

If you nonetheless want to use the notebook, you can just remove the line causing the problem: the import is not used anywhere else.

I think this answers your question, but don't hesitate to reopen the issue should it not.
Also don't hesitate to open new issues if you have other questions.

**Comment by sophie7** [comment]
thanks a lot, yes the training_scripts works.
